version: '2'
services:  
  mysql:
    image: mysql
    volumes:
      - cluster-db-data:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=jamfsoftware
      - MYSQL_PASSWORD=jamfsw03
      - MYSQL_DATABASE=jamfsoftware

  master-jss:
    build:
      context: .
      dockerfile: Dockerfile.tomcat80.jre8
    ports:
      - "8444:8443"
      - "9080:8080"
    links:
      - mysql:db
      - logshipper
    depends_on:
      - mysql
    environment:
      - JSS_DB_HOST=db
      - JSS_DB_PORT=3306
      - JSS_DB_NAME=jamfsoftware
      - JSS_DB_USERNAME=jamfsoftware
      - JSS_DB_PASSWORD=jamfsw03
      - JSS_LOG4J_HOST=logshipper
      - JSS_LOG4J_PORT=4560

  slave-jss:
    build:
      context: .
      dockerfile: Dockerfile.tomcat80.jre8
    ports:
      - "8446:8443"
      - "9081:8080"
    links:
      - mysql:db
      - logshipper
    depends_on:
      - mysql
    environment:
      - JSS_DB_HOST=db
      - JSS_DB_PORT=3306
      - JSS_DB_NAME=jamfsoftware
      - JSS_DB_USERNAME=jamfsoftware
      - JSS_DB_PASSWORD=jamfsw03
      - JSS_LOG4J_HOST=logshipper
      - JSS_LOG4J_PORT=4560

  proxy:
    image: haproxy:1.6
    volumes:
      - "./etc/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    links:
      - "master-jss"
      - "slave-jss"
    ports:
      - "10080:80"

  elasticsearch:
    image: elasticsearch

  kibana:
    image: kibana:latest
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch

  logshipper:
    image: logstash:5
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    volumes:
      - "./etc/logstash.conf:/config-dir/logstash.conf"
    ports:
      - 5044
      - 4560
    command: "logstash -f /config-dir/logstash.conf"

volumes:
  cluster-db-data:
    driver: local


  
