version: '2'
services:  
  mysql:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=jamfsoftware
      - MYSQL_PASSWORD=jamfsw03
      - MYSQL_DATABASE=jamfsoftware

  memcached:
    image: memcached

  jss:
    build:
      context: .
      dockerfile: Dockerfile.tomcat80.jre8
    volumes:
      - log-data:/Library/JSS/Logs
    ports:
      - "8444:8443"
      - "9080:8080"
    links:
      - mysql:db
      - logshipper:logshipper
      - memcached:memcached
    depends_on:
      - mysql
      - logshipper
      - memcached
    environment:
      - JSS_DB_HOST=db
      - JSS_DB_PORT=3306
      - JSS_DB_NAME=jamfsoftware
      - JSS_DB_USERNAME=jamfsoftware
      - JSS_DB_PASSWORD=jamfsw03
      - JSS_CACHE_TYPE=memcached
      - JSS_MEMCACHED=1
      - JSS_MEMCACHED_SERVERS_0=memcached:11211
      - JSS_MEMCACHED_TTL=120
      - JSS_LOG4J_ENABLED=1
      - JSS_LOG4J_HOST=logshipper
      - JSS_LOG4J_PORT=4560

  elasticsearch:
    image: elasticsearch

  kibana:
    image: kibana:latest
    ports:
      - "5601:5601"
    volumes:
      - "./etc/kibana.yml:/etc/kibana/kibana.yml:ro"
    links:
      - elasticsearch:elasticsearch

  logshipper:
    build:
      dockerfile: Dockerfile.logstash-jmx
      context: .
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    volumes:
      - "./etc/logstash.conf:/config-dir/logstash.conf"
      - "./etc/jmx.json:/config-dir/jmx.json"
    ports:
      - 5044
      - 4560
    command: "logstash -f /config-dir/logstash.conf"

  dash:
    image: bruienne/macdash:latest
    depends_on:
      - jss
    ports:
      - "8445:8000"
    links:
      - jss:jss
    environment:
      - JSS_URL=https://jss:8444
      - JSS_USER=admin
      - JSS_PASSWORD=password

  samba:
    image: dperson/samba:latest
    ports:
      - "7139:139"
      - "7445:445"
    volumes:
      - "./distribution_point:/distribution_point"
    command:
      - "-u"
      - "jss;jss"
      - "-s"
      - "distribution_point;/distribution_point;yes;no;yes;all;jss"
      - "-p"
    environment:
      - TZ=UTC


volumes:
  db-data:
    driver: local
  log-data:
    driver: local


  
