version: '2'
services:  
  mysql:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
      - "./etc/mysql.d:/etc/mysql/conf.d:ro"
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=jamfsoftware
      - MYSQL_PASSWORD=jamfsw03
      - MYSQL_DATABASE=jamfsoftware

  jss:
    build:
      context: .
      dockerfile: Dockerfile.tomcat80.jre8
    volumes:
      - log-data:/Library/JSS/Logs
    ports:
      - "8444:8443"
      - "9080:8080"
      - "9000:9000"  # JMX
    links:
      - mysql:db
      # - logshipper:logshipper
    environment:
      - JSS_DB_HOST=db
      - JSS_DB_PORT=3306
      - JSS_DB_NAME=jamfsoftware
      - JSS_DB_USERNAME=jamfsoftware
      - JSS_DB_PASSWORD=jamfsw03
      - JSS_LOG4J_ENABLED=1
      - JSS_LOG4J_HOST=logshipper
      - JSS_LOG4J_PORT=4560
      - JSS_HIBERNATE_SESSION_LOG=true
      - JSS_HIBERNATE_SHOW_SQL=true
      

  elasticsearch:
    image: elasticsearch

  kibana:
    image: kibana:latest
    ports:
      - "5601:5601"
    volumes:
      - "./etc/kibana.yml:/etc/kibana/kibana.yml:ro"
    links:
      - elasticsearch:elasticsearch

  logshipper:
    build:
      dockerfile: Dockerfile.logstash-jmx
      context: .
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - jss:jss
    volumes:
      - "./etc/logstash.conf:/config-dir/logstash.conf"
      - "./etc/jmx.json:/config-dir/jmx/jmx.json"
    ports:
      - 5044
      - 4560
    command: "logstash -f /config-dir/logstash.conf"

volumes:
  db-data:
    driver: local
  log-data:
    driver: local


  
