version: '2'
services:  
  db:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
#      - "./etc/mysql.d:/etc/mysql/conf.d:ro"
    ports:
      - "13306:3306"
    networks:
      - jss
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=jamfsoftware
      - MYSQL_PASSWORD=jamfsw03
      - MYSQL_DATABASE=jamfsoftware

  jss:
    build:
      context: .
      dockerfile: Dockerfile.tomcat80.jre8
    volumes:
      - log-data:/Library/JSS/Logs
    ports:
      - "8444:8443"
      - "9080:8080"
      - "8999:8999"  # JMX eg jconsole hostName:portNum
    networks:
      - jss
      - default
    environment:
      - JSS_DB_HOST=db
      - JSS_DB_PORT=3306
      - JSS_DB_NAME=jamfsoftware
      - JSS_DB_USERNAME=jamfsoftware
      - JSS_DB_PASSWORD=jamfsw03
      - JSS_LOG4J_ENABLED=1
      - JSS_LOG4J_HOST=logshipper
      - JSS_LOG4J_PORT=4560
      - JSS_HIBERNATE_SESSION_LOG=true
      - JSS_HIBERNATE_SHOW_SQL=true
      

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    volumes:
      - "elasticsearch-data:/usr/share/elasticsearch/data"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    ports:
      - 9200:9200
    networks:
      - jss
      - default

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.1
    ports:
      - 5601:5601
    networks:
      - jss
      - default
    volumes:
      - "./etc/kibana.yml:/etc/kibana/kibana.yml:ro"

  logshipper:
    build:
      dockerfile: Dockerfile.logstash-jmx
      context: .
    networks:
      - jss
    volumes:
      - "./etc/logstash.conf:/config-dir/logstash.conf"
      - "./etc/jmx.json:/config-dir/jmx/jmx.json"
    ports:
      - 5044
      - 4560
    command: "logstash -f /config-dir/logstash.conf"

volumes:
  db-data:
    driver: local
  log-data:
    driver: local
  elasticsearch-data:
    driver: local

networks:
  jss:


  
